version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: pokedex_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokedex
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: pokedex_backend
    restart: always
    command: pnpm run dev
    ports:
      - '3000:3000'
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/node_modules
    working_dir: /app/apps/backend

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: pokedex_frontend
    restart: always
    command: pnpm run start
    ports:
      - '4200:4200'
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/node_modules
    working_dir: /app/apps/frontend

volumes:
  pg_data:
